### ISSUE TITLE
Improve the Study Screen

### ISSUE THREAD

**Issue by jordan-powers** [Quizlingo/quizlingo#23]
Problem
---
The study screen does not look correct horizontal.
It fails silently if the user denies microphone permissions to the application. 
It only allows studying by voice, it does not allow voiceless studying.
It does not display deck progress.

Do This
---
Either fix the layout to work in landscape or disable landscape orientation.
Show a dialogue/error message if the user denies microphone permissions.
Allow the user to somehow "flip" the card and show the answer.
Show a progress bar or counter of current progress.

Background
---

**Comment by r6holt** [comment]
issue has a pull request approved
